var searchData=
[
  ['udf_0',['UDF',['../structkuzu_1_1function_1_1_u_d_f.html',1,'kuzu::function']]],
  ['udttypeinfo_1',['UDTTypeInfo',['../classkuzu_1_1common_1_1_u_d_t_type_info.html',1,'kuzu::common']]],
  ['unarycastfunctionwrapper_2',['UnaryCastFunctionWrapper',['../structkuzu_1_1function_1_1_unary_cast_function_wrapper.html',1,'kuzu::function']]],
  ['unarycaststringfunctionwrapper_3',['UnaryCastStringFunctionWrapper',['../structkuzu_1_1function_1_1_unary_cast_string_function_wrapper.html',1,'kuzu::function']]],
  ['unarycastunionfunctionwrapper_4',['UnaryCastUnionFunctionWrapper',['../structkuzu_1_1function_1_1_unary_cast_union_function_wrapper.html',1,'kuzu::function']]],
  ['unaryfunctionexecutor_5',['UnaryFunctionExecutor',['../structkuzu_1_1function_1_1_unary_function_executor.html',1,'kuzu::function']]],
  ['unaryfunctionwrapper_6',['UnaryFunctionWrapper',['../structkuzu_1_1function_1_1_unary_function_wrapper.html',1,'kuzu::function']]],
  ['unarynestedtypefunctionwrapper_7',['UnaryNestedTypeFunctionWrapper',['../structkuzu_1_1function_1_1_unary_nested_type_function_wrapper.html',1,'kuzu::function']]],
  ['unarysequencefunctionwrapper_8',['UnarySequenceFunctionWrapper',['../structkuzu_1_1function_1_1_unary_sequence_function_wrapper.html',1,'kuzu::function']]],
  ['unarystringfunctionwrapper_9',['UnaryStringFunctionWrapper',['../structkuzu_1_1function_1_1_unary_string_function_wrapper.html',1,'kuzu::function']]],
  ['unarystructfunctionwrapper_10',['UnaryStructFunctionWrapper',['../structkuzu_1_1function_1_1_unary_struct_function_wrapper.html',1,'kuzu::function']]],
  ['unaryudfexecutor_11',['UnaryUDFExecutor',['../structkuzu_1_1function_1_1_unary_u_d_f_executor.html',1,'kuzu::function']]],
  ['unaryudffunctionwrapper_12',['UnaryUDFFunctionWrapper',['../structkuzu_1_1function_1_1_unary_u_d_f_function_wrapper.html',1,'kuzu::function']]],
  ['union_5fentry_5ft_13',['union_entry_t',['../structkuzu_1_1common_1_1union__entry__t.html',1,'kuzu::common']]],
  ['uniontype_14',['UnionType',['../structkuzu_1_1common_1_1_union_type.html',1,'kuzu::common']]],
  ['unionvector_15',['UnionVector',['../classkuzu_1_1common_1_1_union_vector.html',1,'kuzu::common']]],
  ['uuid_16',['UUID',['../structkuzu_1_1common_1_1_u_u_i_d.html',1,'kuzu::common']]]
];
